"""update project table

Revision ID: dadd863d9443
Revises: 
Create Date: 2025-05-08 13:01:16.121231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dadd863d9443'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sandStoneCount', sa.Integer(), nullable=False),
    sa.Column('sandStoneCoverage', sa.Float(), nullable=False),
    sa.Column('siltStoneCount', sa.Integer(), nullable=False),
    sa.Column('siltStoneCoverage', sa.Float(), nullable=False),
    sa.Column('segmentedImageURL', sa.String(length=264), nullable=False),
    sa.Column('postDate', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    op.drop_table('user')
    # ### end Alembic commands ###
